### ISSUE TITLE
[Feature Request] Support i18n

### ISSUE THREAD

**Issue by Dafrok** [nohello-net/nohello-net.github.io#12]
This website is the best "nohello" I've ever seen, but it doesn't support i18n. Do you have any plans to support i18n and a11y? I am willing to contribute the Chinese version for this great website.

**Comment by notjosh** [comment]
That's a great idea! I'll take a look at setting up the scaffolding for it and let you know.

**Comment by angeliski** [comment]
Hey @notjosh Could I help in something?

**Comment by notjosh** [comment]
Hiya @angeliski ! I'm working on it at the moment (#15) and it's nearly ready. I'll bump this issue when it's done :)

**Comment by angeliski** [comment]
Amazing! I will help to translate to Portuguese when it is done, let me know

**Comment by notjosh** [comment]
Okay, I thiiiiink it's done enough for now. I've added some [notes in the README](https://github.com/nohello-net/site#translators) on how you can contribute translations, if you'd like.

I haven't decided how the workflow to get languages into the site should go yet (there are a couple of manual code steps I haven't automated yet!), but please open an issue for a specific translation and we'll figure out how to get it live :)
